# Generated by Django 2.2.4 on 2019-08-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190805_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='chargeable',
            field=models.BooleanField(default=False),
        ),
    ]
