# Generated by Django 2.2.4 on 2019-08-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_option_chargeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditcard',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
